const arr = [
    {
      sr : "Sr.",
      title : "TITLE",
      difficulty : "DIFFICULTY",
      category : "CATEGORY",
    },
    {
     id : "two-sum",
      title: "Two Sum",
      difficulty: "Easy",
      category: "Array",
      order: 1,
      videoId: "8-k1C6ehKuw",
      description : "Given an array of integers nums and an integer target, returnindices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use thesame element twice. You can return the answer in any order. ",
      input : "nums = [2,7,11,15], target = 9",
      output : '[0,1]',
      inputt :"nums = [3,2,4], target = 6 ",
      outputt : " [1,2]",
    },
      {
        id: "reverse-linked-list",
        title: "Reverse Linked List",
        difficulty: "Hard",
        category: "Linked List",
        order: 2,
        videoId: "",
      },
      {
        id: "jump-game",
        title: "Jump Game",
        difficulty: "Medium",
        category: "Dynamic Programming",
        order: 3,
        videoId: "",
      },
      {
        id: "valid-parentheses",
        title: "Valid Parentheses",
        difficulty: "Easy",
        category: "Stack",
        order: 4,
        videoId: "xty7fr-k0TU",
      },
      {
        id: "search-a-2d-matrix",
        title: "Search a 2D Matrix",
        difficulty: "Medium",
        category: "Binary Search",
        order: 5,
        videoId: "ZfFl4torNg4",
      },
      {
        id: "container-with-most-water",
        title: "Container With Most Water",
        difficulty: "Medium",
        category: "Two Pointers",
        order: 6,
        videoId: "",
      },
      {
        id: "merge-intervals",
        title: "Merge Intervals",
        difficulty: "Medium",
        category: "intervals",
        order: 7,
        videoId: "",
      },
      {
        id: "maximum-depth-of-binary-tree",
        title: "Maximum Depth of Binary Tree",
        difficulty: "Easy",
        category: "Tree",
        order: 8,
        videoId: "4qYTqOiRMoM",
      },
      {
        id: "best-time-to-buy-and-sell-stock",
        title: "Best Time to Buy and Sell Stock",
        difficulty: "Easy",
        category: "Array",
        order: 9,
        videoId: "",
      },
      {
        id: "subsets",
        title: "Subsets",
        difficulty: "Medium",
        category: "Backtracking",
        order: 10,
        videoId: "",
      },

]

export default arr;